version: '3'

services:
    web:
        container_name: isccr-web
        build: .
        volumes:
            - .:/code
        ports:
            - "80:8888"
        depends_on:
            - db
    coblo:
        container_name: isccr-observer-coblo
        build: .
        command: poetry run python -m isccr.observers.coblo
        depends_on:
            - db
            - web
    bloxberg:
        container_name: isccr-observer-bloxberg
        build: .
        command: poetry run python -m isccr.observers.bloxberg
        depends_on:
            - db
            - web
    db:
        container_name: isccr-db
        image: postgres
        environment:
            - POSTGRES_DB=isccr
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
