version: '3'

services:
    web:
        container_name: isccr-web
        build: .
        command: >
            bash -c "poetry run python manage.py migrate &&
                     poetry run python manage.py collectstatic --no-input &&
                     poetry run gunicorn isccr.wsgi:application --bind 0.0.0.0:8888 --workers 4 --timeout 60"
        ports:
            - "8888:8888"
        depends_on:
            - db
    coblo:
        container_name: isccr-observer-coblo
        build: .
        command: poetry run python -m isccr.observers.coblo
        depends_on:
            - db
            - web
    bloxberg:
        container_name: isccr-observer-bloxberg
        build: .
        command: poetry run python -m isccr.observers.bloxberg
        depends_on:
            - db
            - web
    db:
        container_name: isccr-db
        image: postgres
        environment:
            - POSTGRES_DB=isccr
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    caddy:
        container_name: isccr-caddy
        image: "caddy:2.4.6"
        restart: unless-stopped
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile  # configuration
            - caddy-config:/config  # configuation autosaves
            - caddy-data:/data  # saving certificates
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web

volumes:
  caddy-config:
  caddy-data:
