# Generated by Django 3.1.1 on 2020-09-20 17:52

from django.db import migrations, models
import django.db.models.constraints
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("slug", models.SlugField()),
                ("url_template", models.CharField(blank=True, max_length=256)),
            ],
            options={
                "verbose_name": "Chain",
                "verbose_name_plural": "Chains",
            },
        ),
        migrations.CreateModel(
            name="IsccID",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "iscc_id",
                    models.CharField(
                        help_text="ISCC-ID - digital asset identifier",
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ISCC-ID",
                    ),
                ),
                (
                    "iscc_code",
                    models.CharField(
                        help_text="ISCC-CODE - digital asset descriptor",
                        max_length=256,
                        verbose_name="ISCC-CODE",
                    ),
                ),
                (
                    "iscc_tophash",
                    models.CharField(
                        help_text="Cryptographic hash of digital asset",
                        max_length=256,
                        verbose_name="ISCC-TOPHASH",
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        help_text="PUBLIC-KEY or WALLET-ADDRESS of DECLARING PARTY",
                        max_length=256,
                    ),
                ),
                (
                    "iscc_seed_title",
                    models.CharField(blank=True, max_length=128, verbose_name="title"),
                ),
                (
                    "iscc_seed_extra",
                    models.TextField(blank=True, max_length=4096, verbose_name="extra"),
                ),
                (
                    "iscc_mutable_metadata",
                    models.JSONField(null=True, verbose_name="mutable metadata"),
                ),
                (
                    "src_chain_idx",
                    models.PositiveBigIntegerField(
                        help_text="N-th ISCC Decleration on source ledger",
                        verbose_name="ledger index",
                    ),
                ),
                (
                    "src_block_hash",
                    models.CharField(
                        help_text="Hash of block that includes the ISCC-DECLARATION",
                        max_length=128,
                        verbose_name="block hash",
                    ),
                ),
                (
                    "src_tx_hash",
                    models.CharField(
                        help_text="Hash of transaction that includes the ISCC-DECLERATION",
                        max_length=128,
                        verbose_name="transaction hash",
                    ),
                ),
                (
                    "src_tx_out_idx",
                    models.PositiveSmallIntegerField(
                        help_text="Output index that includes ISCC-DECLERATION (UTXO based chains)",
                        null=True,
                        verbose_name="transaction output",
                    ),
                ),
                ("src_time", models.DateTimeField()),
                (
                    "revision",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times updated"
                    ),
                ),
                (
                    "src_chain",
                    models.ForeignKey(
                        help_text="Source Ledger/Blockchain",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.chain",
                        verbose_name="Ledger",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISCC-ID",
                "verbose_name_plural": "ISCC-IDs",
            },
        ),
        migrations.AddConstraint(
            model_name="isccid",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["IMMEDIATE"],
                fields=("iscc_id", "iscc_code", "actor"),
                name="unique-entry",
            ),
        ),
    ]
