# Generated by Django 3.1.1 on 2021-09-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isccid',
            name='src_time',
            field=models.DateTimeField(verbose_name='timestamp'),
        ),
        migrations.AddIndex(
            model_name='isccid',
            index=models.Index(fields=['src_time'], name='core_isccid_src_tim_fc0642_idx'),
        ),
    ]
